language: python
python:
  - '3.5'
install: 'pip install -r requirements.lst'
before_script: "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
script: python tests.py
notifications:
  email:
     - henri@nerv.fi
